#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

SERVIDORES=(
	"10.10.100.254-HOME:Router	" 
	"10.10.100.10-HOME:ktulu+	" 
	"10.10.100.3-HOME:mini_servito	" 
	"10.10.100.1-HOME:servito	" 
	"10.10.100.2-HOME:servito_vm	" 
	)

for servidor in "${SERVIDORES[@]}";
do
	pos=`echo ${servidor} | grep -aob '-' --color=never | \grep -oE '^[0-9]+'`	
        ping -c 1 ${servidor:0:$pos} >> /dev/null
        resultado=$?
        if [ "$resultado" -gt 0 ]; then
                echo -e "${servidor}\t${RED}[DOWN]${NC}"
        else
                echo -e "${servidor}\t${GREEN}[ OK ]${NC}"
        fi

done    


