#!/bin/bash

function montarSERVITO {

	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //192.168.10.2/Documentos/ ~/nas/servito/documentos
	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //192.168.10.2/Downloads/ ~/nas/servito/downloads
	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //192.168.10.2/Movies/ ~/nas/servito/movies
	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //192.168.10.2/Series/ ~/nas/servito/series
	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //192.168.10.2/Programas/ ~/nas/servito/programas
	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //192.168.10.2/backup/ ~/nas/servito/backup
	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //192.168.10.2/videos/ ~/nas/servito/videos

}

ping -c 1 '192.168.10.2' > /dev/null
resultado=$?
echo "respuesta ----> $resultado"
if [ "$resultado" -gt 0 ]; then
	echo "SERVITO fuera Linea"
	echo "--> el servidor se enciende automáticamente a las 8 AM"
else
	echo "---------------------------"
	echo "SERVITO en Linea"
	echo "Montando recurrsos samba..."
	echo "---------------------------"
	montarSERVITO
fi
