#!/bin/bash

function montarSERVITO {

	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //10.10.100.1/Documentos/ ~/nas/servito/documentos
	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //10.10.100.1/Downloads/ ~/nas/servito/downloads
	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //10.10.100.1/Movies/ ~/nas/servito/movies
	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //10.10.100.1/Series/ ~/nas/servito/series
	sudo mount -t cifs -o rw,credentials=/home/lapi/.smbcredentials,noperm,uid=1008,gid=1008 //10.10.100.1/Programas/ ~/nas/servito/programas


}

ping -c 1 10.10.100.1 > /dev/null
resultado=$?
echo "respuesta ----> $resultado"
if [ "$resultado" -gt 0 ]; then
	echo "SERVITO fuera Linea"
	echo "--> el servidor se enciende automáticamente a las 8 AM"
else
	echo "---------------------------"
	echo "SERVITO en Linea"
	echo "Montando recurrsos samba..."
	echo "---------------------------"
	montarSERVITO
fi
